os: unstable
environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: 1701b1a6e96fb256b57fd72c648372858f9eebbd

  matrix:
  - nodejs_version: "7"

platform:
- x64

install:
- ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform;
- ps: $env:Path += ";$(pwd)\node_modules\.bin";
- ps: >
    @{
      "nodejs_version" = $env:nodejs_version
      "platform" = $env:platform
      "node binary version" = $(node -v)
      "node platform@arch" = $(node -p 'process.platform + process.arch')
      "npm version" = $(npm -v)
      "APPVEYOR_REPO_COMMIT_MESSAGE" = $env:APPVEYOR_REPO_COMMIT_MESSAGE
      "git latest tag" = "$(git describe --tags --always HEAD)"
      "appveyor_repo_tag" = $env:appveyor_repo_tag
      "electron_version" = $env:electron_version
    } | Out-String | Write-Host;
# work around bug in npm 2.15.1 where checksums were coming back bad (node 0.12)
- ps: >
    if ($(npm -v) -eq "2.15.1") {
      npm install -g npm@3 | Write-Host;
    }
    npm -v | Write-Host;
# work around an issue with node-gyp v3.3.1 and node 4x
# package.json has no certificates in it so we're cool
# https://github.com/nodejs/node-gyp/issues/921
- ps: npm config set -g cafile=package.json | Write-Host;
- ps: npm config set -g strict-ssl=false | Write-Host;

# Check if we're building the latest tag, if so
# then we publish the binaries if tests pass.
- ps: >
    if ($env:appveyor_repo_tag -match "true" -and ("$(git describe --tags --always HEAD)" -eq $env:appveyor_repo_tag_name)) {
      $env:publish_binary = 1;
    } else {
      $env:publish_binary = 0;
    }
    true;
- ps: >
    if ($env:publish_binary -eq 1) {
      "We're publishing a binary!" | Write-Host
    } else {
      "We're not publishing a binary" | Write-Host
    }
    true;
# Cleanup the output of npm
- ps: >
    npm config set progress false
    npm config set spin false
# We don't currently have a port to test on windows
# - ps: $env:TEST_PORT = "COM1";

# Setup Electron variables
- ps: >
    if ($env:electron_version) {
      "We're an electron build, setup variables" | Write-Host
      $env:npm_config_target = $env:electron_version
      $env:npm_config_disturl = "https://atom.io/download/atom-shell"
      $env:npm_config_runtime = "electron"
      if ($env:plaftorm -eq "x86") {
        $env:npm_config_arch = "ia32"
      } else {
        $env:npm_config_arch = "x64"
      }
      "Install electron and electron-mocha" | Write-Host
      npm install -g electron@$env:electron_version
      npm install electron-mocha
    }
    true;
# Disable windows incompatible port tests
- ps: >
    $env:DISABLE_PORT_FEATURE = "open.unlock,baudrate.25000"
build_script:
- npm install --build-from-source --msvs_version=2015

test_script:
- ps: >
    if ($env:nodejs_version -ne "4") {
      npm run lint
    }
    true;
# If we run npm test in powershell it'll have the wrong encoding
# so we have to do it like this

- IF DEFINED electron_version (electron test/electron)
- IF NOT DEFINED electron_version (node ./)
- IF NOT DEFINED electron_version (npm test)

- IF %PUBLISH_BINARY% == 1 (node-pre-gyp package 2>&1)
- IF %PUBLISH_BINARY% == 1 (node-pre-gyp-github publish --release 2>&1)
- IF %PUBLISH_BINARY% == 1 (node-pre-gyp clean)
- IF %PUBLISH_BINARY% == 1 (npm install --fallback-to-build=false)

after_test:
- pip install codecov && codecov

deploy: OFF

matrix:
  fast_finish: true